site_name: aWords

# Repository
repo_name: 'keygenqt/flutter-aWords'
repo_url: 'https://github.com/keygenqt/flutter-aWords'
site_dir: 'flutter-aWords'
site_url: 'https://keygenqt.github.io/flutter-aWords/'

# Navigation
nav:
  - Home:
      - index.md
      - Server: server/index.md
      - Web: web/index.md
      - Mobile: mobile/index.md
  - Server:
      - Overview:
          - server/index.md
      - Methods:
          - Auth:
              - Login: server/methods/login.md
              - Registration: server/methods/registration.md
              - Logout: server/methods/logout.md
          - Users:
              - User Create: server/methods/users_create.md
              - User Update: server/methods/users_update.md
              - User Delete: server/methods/users_delete.md
              - User Item: server/methods/users_item.md
              - User List: server/methods/users_list.md
          - Common:
              - Errors: server/methods/common_errors.md
      - Libraries: server/libraries.md
      - Dartdoc: /flutter-aWords/server_doc/api/
      - Go to API: https://awords-api.keygenqt.com/
  - Web:
      - Overview:
          - web/index.md
      - Libraries: web/libraries.md
      - Dartdoc: /flutter-aWords/web_doc/api/
      - Go to API: https://awords.keygenqt.com/
  - Mobile:
      - Overview:
          - mobile/index.md
      - Applications:
          - Android:
              - About: mobile/android/about.md
              - Libraries: mobile/android/libraries.md
          - Aurora:
              - About: mobile/aurora/about.md
              - Libraries: mobile/aurora/libraries.md

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - icons

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/keygenqt
    - icon: fontawesome/brands/telegram
      link: https://t.me/keygenqt
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vitaliy-zarubin-6a8257150/

# Custom CSS
extra_css:
  - /flutter-aWords/custom.css

# Configuration
theme:
  name: 'material'
  custom_dir: docs/assets
  language: 'en'
  favicon: images/favicon.ico
  icon:
    logo: custom/icon
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.prune
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono