name: server_awords
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  archive: ^3.3.6
  args: ^2.3.1
  mason_logger: ^0.2.4
  pub_updater: ^0.2.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
