name: ci

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Server app pub get
        working-directory: ./apps/server
        run: dart pub get

      - name: Server app build_runner
        working-directory: ./apps/server
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Server app dart doc
        working-directory: ./apps/server
        run: dart doc .

      - name: Server app move doc
        working-directory: ./apps/server
        run: |
          mv doc ../../docs/server_doc

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material

      - name: Build site
        run: |
          mkdocs gh-deploy --force