name: ci

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Pub get
        run: cd apps/server && dart pub get

      - name: Dart build_runner
        run: cd apps/server && dart run build_runner build

      - name: Gen server dart doc
        run: cd apps/server && dart doc .

      - name: Move doc server
        working-directory: ./apps/server
        run: |
          mv doc ../../docs/server_doc

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material

      - name: Build site
        run: |
          mkdocs gh-deploy --force